```{r input-setup, include=FALSE, purl=FALSE}
knitr::opts_knit$set(unnamed.chunk.label = "input-")
```

# Getting your data in right format

Your data need to be a matrix (not dataframe nor a **ts** object) with time across the columns ($n \times T$ matrix).  The **MARSS** functions assume discrete time steps and you will need a column for each time step.  Replace any missing time steps with NA.

A \,\textbf{R} **ts** object (time series object) stores information about the time steps of the data and often seasonal information (the quarter or month).  **MARSS** needs this information in matrix form.  If you have your data in **ts** form, then you may be using year and season (quarter, month) as covariates to estimate trend and seasonality.  Here is how to get your **ts** into the form that MARSS wants.

Here is how to get your **ts** object into the form that MARSS wants.

## Univariate **ts** object

This converts a univariate **ts** object with year and quarter into a matrix with a row for the response (here called `Temp`), year, and quarter.  

```
z <- ts(rnorm(10), frequency = 4, start = c(1959, 2))
dat <- data.frame(Yr = floor(time(z) + .Machine$double.eps), 
      Qtr = cycle(z), Temp=z)
dat <- t(dat)
class(dat)
```
Notice that the class of `dat` is matrix, which is what we want. There are three rows, first is the reponse and the second and third are the covariates, Year and Quarter.  When you call MARSS, `dat["Temp",]` is the data. `dat[c("Yr","Qtr"),]` are your covariates.  

## Multivariate **ts** object

In this example, we have two temperature readings, our responses, and a salinity reading, a covariate. The data are monthly.

```
z <- ts(matrix(rnorm(300), 100, 3), start = c(1961, 1),
     frequency = 12, names=c("Temp1","Temp2","Sal"))
dat <- data.frame(Yr = floor(time(z) + .Machine$double.eps), 
     Month = cycle(z), z)
dat <- t(dat)
```

When you call MARSS, `dat[c("Temp1","Temp2"),]` are the data and `dat[c("Yr","Month","Sal"),]` are your covariates.  

See the *MARMES* chapters that discuss seasonality for examples of how to model season.  The brute force method of treating month or quarter as a factor requires estimation of more parameters than is necessary in many cases.

