```{r em-setup, include=FALSE, purl=FALSE}
knitr::opts_knit$set(unnamed.chunk.label = "em-")
```

# Algorithm notes and cautions {#chap-algorithm-notes}

The **MARSS** package fits models via maximum likelihood. The **MARSS** package is unusual among packages for fitting MARSS models in that fitting is performed via a constrained EM algorithm [@Holmes2013] based on a vectorized form of Equation \@ref(eq:marss).  

Although fitting via the BFGS algorithm is also provided using `method="BFGS"` and the optim function in R, the examples in this guide use the EM algorithm primarily because it gives robust estimation for datasets replete with missing values and for high-dimensional models with various constraints. However, there are many models/datasets where BFGS is faster and we typically try both for problems.  All the EM code in the **MARSS** package is currently in native R.  Thus the model fitting with the EM algorithm is rather slow.  

## Properly constrained models

Specification of a properly constrained model with a unique solution is the responsibility of the user because `MARSS()` has no way to tell if you have specified an insufficiently constrained model---with correspondingly an infinite number of solutions. 

How do you know if the model is properly constrained?  If you are using a MARSS model form that is widely used, then you can probably assume that it is properly constrained. If you go to papers where someone developed the model or method, the issue of constraints necessary to ensure "identifiability" will likely be addressed if it is an issue.  Are you fitting novel MARSS models? Then you will need to do some study on identifiability in this class of models using textbooks.  Often textbooks do not address identifiability explicitly.  Rather it is addressed implicitly by only showing a model constructed in such a way that it is identifiable.  In our work, if we suspect identification problems, we will often first do a Bayesian analysis with flat priors and look for oddities in the posteriors, such as ridges, plateaus or bimodality.
 
## Notes on the Kalman filter

The classic Kalman filter/smoother algorithm, as shown in page  331-335 in @ShumwayStoffer2006, is based on the original smoother presented in @Rauch1963. This Kalman filter is provided in function `MARSSkfss()`, but the default Kalman filter and smoother used in the **MARSS** package is based on the algorithm in @KohnAnsley1989 and papers by Koopman et al. This Kalman filter and smoother is provided in the **KFAS** package [@R-KFAS].  Table 2 in @Koopman1993 indicates that the classic algorithm is 40-100 times slower than the algorithm given in @KohnAnsley1989, @Koopman1993, and @Koopmanetal1998. 

The **MARSS** package function `MARSSkfas()` provides a translator between the model objects in **MARSS** and those in **KFAS** so that the **KFAS** functions can be used.  `MARSSkfas()` also includes a lag-one covariance smoother algorithm as this is not output by the **KFAS** functions, and it provides proper formulation of the priors so that one can use the **KFAS** functions when the prior on the states is set at $t=0$ instead of $t=1$. Simply off-setting your data to start at t=2 and sending that value to $t_{init}=1$ in the **KFAS** Kalman filter would not be mathematically correct!

## Notes on the EM algorithm

EM algorithms will quickly get in the vicinity of the maximum likelihood, but the final approach to the maximum is generally slow relative to quasi-Newton methods.  On the flip side, EM algorithms are quite robust to initial conditions choices and can be extremely fast at getting close to the MLE values for high-dimensional models.  The **MARSS** package also allows one to use the BFGS method to fit MARSS models, thus one can use an EM algorithm to *get close* and then the BFGS algorithm to polish off the estimate. 

Restricted maximum-likelihood algorithms are also available for AR(1) state-space models, both univariate [@Staplesetal2004] and multivariate [@HinrichsenHolmes2009].  REML can give parameter estimates with lower variance than plain maximum-likelihood algorithms. Another maximum-likelihood method is data-cloning which adapts MCMC algorithms used in Bayesian analysis for maximum-likelihood estimation [@Leleetal2007].  

Missing values\index{missing values} are seamlessly accommodated with the EM algorithm in the **MARSS** package.  Simply specify missing data with NAs.  The likelihood computations are exact and will deal appropriately with missing values.  However, no innovations, referring to the non-parametric bootstrap developed by Stoffer and Wall (1991), bootstrapping can be done if there are missing values.  Instead parametric bootstrapping must be used.

## Bias in variance estimates

You should be aware that maximum-likelihood estimates of variance in MARSS models are fundamentally biased, regardless of the algorithm used.  This bias is more severe when one or the other of $\mathbf{R}$ or $\mathbf{Q}$ is very small, and the bias does not go to zero as sample size goes to infinity.  The bias arises because variance is constrained to be positive.  Thus if $\mathbf{R}$ or $\mathbf{Q}$ is essentially zero, the mean estimate will not be zero and thus the estimate  will be biased high while the corresponding bias of the other variance will be biased low.  You can generate unbiased variance estimates using a bootstrap estimate of the bias.  The function `MARSSparamCIs()` will do this.  However be aware that adding an  estimated bias to a parameter estimate will lead to an increase in the variance of your parameter estimate.  The amount of variance added will depend on sample size.

## Careful if specifying a prior on initial conditions

You should also be aware that mis-specification of the prior on the initial states ($\boldsymbol{\pi}$ and $\boldsymbol{\Lambda}$) can have catastrophic effects on your parameter estimates if your prior conflicts with the distribution of the initial states implied by the MARSS model.  These effects can be very difficult to detect because the model will appear to be well-fitted.  Unless you have a good idea of what the parameters should be, you might not realize that your prior conflicts. 

The default behavior for `MARSS()` is to set $\boldsymbol{\Lambda}$ to zero and estimate $\boldsymbol{\pi}$. This does not put any constraints on $\boldsymbol{\Lambda}$ (there is no $\boldsymbol{\Lambda}$ to put constraints on) and circumvents this problem.  However if you plan to put contraints on $\boldsymbol{\pi}$ or $\boldsymbol{\Lambda}$, you should verse yourself in the most common problems. The common problems we have found with priors on $\mathbf{x}_0$ are the following.  Problem 1) The correlation structure in $\boldsymbol{\Lambda}$ (whether the prior is diffuse or not) does not match the correlation structure in $\mathbf{x}_0$ implied by your model.  For example, you specify a diagonal $\boldsymbol{\Lambda}$ (independent states), but the implied distribution has correlations. Problem 2) The correlation structure in $\boldsymbol{\Lambda}$ does not match the structure in $\mathbf{x}_0$ implied by constraints you placed on $\boldsymbol{\pi}$.  For example, you specify that all values in $\boldsymbol{\pi}$ are shared, yet you specify that $\boldsymbol{\Lambda}$ is diagonal (independent).  

Unfortunately, using a diffuse prior does not help with these two problems because  the diffuse prior still has a correlation structure and can still conflict with the implied correlation in $\mathbf{x}_0$.  One way to get around these problems is to set $\boldsymbol{\Lambda}=0$ (a $m \times m$ matrix of zeros) and estimate $\boldsymbol{\pi} \equiv \mathbf{x}_0$ only.  Now $\boldsymbol{\pi}$ is a fixed but unknown (estimated) parameter, not the mean of a distribution.  In this case, $\boldsymbol{\Lambda}$ does not exist in your model and there is no conflict with the model. This is the default behavior of `MARSS()`. Unfortunately estimating $\boldsymbol{\pi}$ as a parameter is not always robust. If you specify that $\boldsymbol{\Lambda}$=0 and specify that $\boldsymbol{\pi}$ corresponds to $\mathbf{x}_0$, but your model *explodes* when run backwards in time, you cannot estimate $\boldsymbol{\pi}$ because you cannot get a good estimate of $\mathbf{x}_0$.  Sometimes this can be avoided by specifying that $\boldsymbol{\pi}$ corresponds to $\mathbf{x}_1$ so that it can be constrained by the data $\mathbf{y}_1$. 

In summary, if the implied correlation structure of your initial states is independent (diagonal variance-covariance matrix), you should generally be ok with a diagonal and high variance prior or with treating the initial states as parameters (with $\boldsymbol{\Lambda}=0$).  But if your initial states have an implied correlation structure that is not independent, then proceed with caution. *With caution* means that you should assume you have problems and test how your model fits with simulated data.

## State-space form of ARMA(p,q) models

There is a large class of models in the statistical finance literature that have the form
\begin{equation*}
\begin{gathered}
\mathbf{x}_{t+1} = \mathbf{B}\mathbf{x}_t + \boldsymbol{\Gamma}\boldsymbol{\eta}_t\\
\mathbf{y}_t = \mathbf{Z}\mathbf{x}_t  + \boldsymbol{\eta}_t\\
\end{gathered}
\end{equation*}
For example, ARMA(p,q) models can be written in this form.  The MARSS model framework in this package will not allow you to write models in that form.  You can put the $\boldsymbol{\eta}_t$ into the $\mathbf{x}_t$ vector and set $\mathbf{R}=0$ to make models of this form using the MARSS form, but the EM algorithm in the MARSS package won't let you estimate parameters because the parameters will drop out of the full likelihood being maximized in the algorithm.  You can try using BFGS by passing in the `method="BFGS"` to the `MARSS()` call.

