# Troubleshooting

\index{troubleshooting}Numerical errors due to ill-conditioned matrices are not uncommon when fitting MARSS models\index{errors!ill-conditioned}\index{troubleshooting!ill-conditioning}\index{likelihood!troubleshooting}. The Kalman and EM algorithms need inverses of matrices. If those matrices become ill-conditioned, for example all elements are close to the same value, then the algorithm becomes unstable.  Warning messages will be printed if the algorithms are becoming unstable\index{troubleshooting!numerical instability} and you can set \verb@control$trace=1@, to see details of where the algorithm is becoming unstable.  Whenever possible, you should avoid using shared $\pipi$ values in your model\footnote{An example of a $\pipi$ with shared values is $\pipi=\bigl[\begin{smallmatrix} a\\a\\a \end{smallmatrix} \bigr]$.}.  The way our algorithm deals with $\LAM$ tends to make this case unstable, especially if $\RR$ is not diagonal.  In general, estimation of a non-diagonal $\RR$ is more difficult, more prone to ill-conditioning, and more data-hungry.

You may also see non-convergence warnings, especially if your MLE model turns out to be degenerate\index{errors!degenerate}\index{troubleshooting!degenerate}\index{troubleshooting!non-convergence}.  This means that one of the elements on the diagonal of your $\QQ$ or $\RR$ matrix are going to zero (are degenerate).  It will take the EM algorithm forever to get to zero.  BFGS will have the same problem, although it will often get a bit closer to the degenerate solution.  If you are using \verb@method="kem"@, MARSS will warn you if it looks like the solution is degenerate. If you use \verb@control=list(allow.degen=TRUE)@, the EM algorithm will attempt to set the degenerate variances to zero (instead of trying to get to zero using an infinite number of iterations).  However, if one of the variances is going to zero, first think about why this is happening.  This is typically caused by one of three problems:  1) you made a mistake in inputting your data, e.g. used -99 as the missing value in your data but did not replace these with NAs before passing to MARSS, 2) your data are not sufficient to estimate multiple variances or 3) your data are inconsistent with the model you are trying fit.

The algorithms in the MARSS package are designed for cases where the $\QQ$ and $\RR$ diagonals are all non-minuscule.  For example, the EM update equation for $\uu$ will grind to a halt (not update $\uu$) if $\QQ$ is tiny (like 1E-7).  Conversely, the BFGS equations are likely to miss the maximum-likelihood when $\RR$ is tiny because then the likelihood surface becomes hyper-sensitive to $\pipi$.   The solution is to use the degenerate likelihood function for the likelihood calculation and the EM update equations.  MARSS will implement this automatically when $\QQ$ or $\RR$ diagonal elements are set to zero and will try setting $\QQ$ and $\RR$ terms to zero automatically if \verb@control$allow.degen=TRUE@.  

One odd case can occur when $\RR$ goes to zero (a matrix of zeros), but you are estimating $\pipi$.  If \verb@model$tinitx=1@, then $\pipi=\xx_1^0$ and $\yy_1-\ZZ\xx_1^0$ can go to 0 as well as $\var(\yy_1-\ZZ\xx_1^0)$ by driving $\RR$  to zero. But as this happens, the log-likelihood associated with $\yy_1$ will go (correctly) to infinity and thus the log-likelihood goes to infinity.  But if you set $\RR=0$, the log-likelihood will be finite.  The reason is that $\RR \approx 0$ and $\RR=0$ specify different likelihoods associated with $\yy_1-\ZZ\xx_1^0$.  With $\RR=0$, $\yy_1-\ZZ\xx_1^0$ does not have a distribution; it is just a fixed value.  So there is no likelihood to go to infinity.  If some elements of the diagonal of $\RR$ are going to zero, you should be suspect of the parameter estimates.  Sometimes the structure of your data, e.g. one data value followed by a long string of missing values, is causing an odd spike in the likelihood at  $\RR \approx 0$.  Try manually setting $\RR$ equal to zero to get the correct log-likelihood\footnote{The likelihood returned when $\RR \approx 0$ is not incorrect.  It is just not the likelihood that you probably want.  You want the likelihood where the $\RR$ term is dropped because it is zero.}.  

\section{Other related packages}
Packages that will do Kalman filtering and smoothing are many, but packages that estimate the parameters in a MARSS model, especially constrained MARSS models, are much less common.  The following are those with which we are familiar, however there are certainly more packages for estimating MARSS models in engineering and economics of which we are unfamiliar.  The MARSS package is unusual in that it uses an EM algorithm for maximizing the likelihood as opposed to a Newton-esque method (e.g. BFGS). The package is also unusual in that it allows you to specify the initial conditions at $t=0$ or $t=1$, allows degenerate models (with some of the diagonal elements of $\RR$ or $\QQ$ equal to zero). Lastly, model specification in the MARSS package  has a one-to-one relationship between the model list in MARSS and the model as you would write it on paper as a matrix equation.  This makes the learning curve a bit less steep.  However, the MARSS package has not been optimized for speed and probably will be really slow if you have time-series data with a lot of time points.

\begin{description}
	\item[atsar] \href{https://nwfsc-timeseries.github.io/atsar/}{atsar} is an \R package we wrote for fitting MARSS models using STAN.  It allows fast and flexible fitting of MARSS models in a Bayesian framework.  Our book from our time-series class has example applications \href{https://nwfsc-timeseries.github.io/atsa-labs/}{Applied Time-Series Analysis for Fisheries and Environmental Sciences}.
  \item[stats] The \verb@stats@ package (part of base R) has functions for fitting univariate structural time series models (MARSS models with a univariate y).  Read the help file at \verb@?StructTS@. The Kalman filter and smoother functions are described here: \verb@?KalmanLike@.
	\item[DLM] \href{https://cran.r-project.org/package=dlm}{DLM} is an \R package for fitting MARSS models.  Our impression is that it is mainly Bayesian focused but it does allow MLE estimation via the \verb@optim()@ function.  It has a book, Dynamic Linear Models with \R  by Petris et al., which has many examples of how to write MARSS models for different applications.
	\item[sspir] \href{https://cran.r-project.org/package=sspir}{sspir} an \R package for fitting ARSS (univariate) models with Gaussian, Poisson and binomial error distributions.  
	\item[dse] \href{https://cran.r-project.org/package=dse}{dse} (Dynamic Systems Estimation) is an \R package for multivariate Gaussian state-space models with a focus on ARMA models.
	\item[SsfPack] \href{http://www.ssfpack.com/}{SsfPack} is a package for Ox/Splus that fits constrained multivariate Gaussian state-space models using mainly (it seems) the BFGS algorithm but the newer versions support other types of maximization.  SsfPack is very flexible and written in C to be fast.  It has been used extensively on statistical finance problems and is optimized for dealing with large (financial) data sets.  It is used and documented in Time Series Analysis by State Space Methods by Durbin and Koopman, An Introduction to State Space Time Series Analysis by Commandeur and Koopman, and Statistical Algorithms for Models in State Space Form: SsfPack 3.0, by Koopman, Shephard, and Doornik.
	\item[Brodgar] The Brodgar software was developed by Alain Zuur to do (among many other things) dynamic factor analysis, which involves a special type of MARSS model.  The methods and many example analyses are given in Analyzing Ecological Data by Zuur, Ieno and Smith.  This is the one package that we are aware of that also uses an EM algorithm for parameter estimation.
	\item[eViews] eViews is a commercial economics software that will estimate at least some types of MARSS models.
	\item[KFAS] The \href{https://cran.r-project.org/package=KFAS}{KFAS} \R package provides a fast Kalman filter and smoother.  Examples in the package show how to estimate MARSS models using the KFAS functions and \R's \verb@optim()@ function.   The MARSS package uses the filter and smoother functions from the KFAS package.
		\item[S+FinMetrics] \href{http://faculty.washington.edu/ezivot/MFTS2ndEditionFinMetrics.htm}{S+FinMetrics} is a S-plus module for fitting MAR models, which are called vector autoregressive (VAR) models in the economics and finance literature.  It has some support for state-space VAR models, though we haven't used it so are not sure which parameters it allows you to estimate.  It was developed by Andrew Bruce, Doug Martin, Jiahui Wang, and Eric Zivot, and it has a book associated with it: Modeling Financial Time Series with S-plus by Eric Zivot and Jiahui Wang.
		\item[kftrack] The \href{https://github.com/positioning/kalmanfilter/wiki}{kftrack} \R package provides a suite of functions specialized for fitting MARSS models to animal tracking data.
\end{description}